### PR TITLE
Fix path of file

### LINKED ISSUE #798: Version 4.1.1 Errors on signature request and on sign attempts
Installed the new release 4.1.1 on NC 23.0.4

New errors when submitting signature request:
```
{"reqId":"2rjwy32NYIuJ81XN0nd1","level":3,"time":"2022-05-05T21:19:20+00:00","remoteAddr":"10.0.1.61","user":"3068AB2C-4706-4705-86D8-F14F237C43DC","app":"PHP","method":"POST","url":"/index.php/apps/libresign/api/0.1/sign/register"
,"message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php#39","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.4.1",
"Exception":{
"Exception":"Error"
,"message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php#39","Code":0,
"Trace":[{"file":"/var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php","line":39,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":240,"function":"getMetadata","class":"OCA\\Libresign\\Service\\PdfParserService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":222,"function":"getFileMetadata","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":172,"function":"saveFile","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Controller/SignFileController.php","line":88,"function":"save","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"requestSign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},
{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},
{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}

{"reqId":"2rjwy32NYIuJ81XN0nd1","level":3,"time":"2022-05-05T21:19:20+00:00","remoteAddr":"10.0.1.61","user":"3068AB2C-4706-4705-86D8-F14F237C43DC","app":"PHP","method":"POST","url":"/index.php/apps/libresign/api/0.1/sign/register"
,"message":"count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php#39","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.4.1",
"Exception":{
"Exception":"Error"
,"message":"count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php#39","Code":0,
"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php","line":39,"function":"count"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":240,"function":"getMetadata","class":"OCA\\Libresign\\Service\\PdfParserService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":222,"function":"getFileMetadata","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":172,"function":"saveFile","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Controller/SignFileController.php","line":88,"function":"save","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"requestSign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},
{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},
{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}

{"reqId":"2rjwy32NYIuJ81XN0nd1","level":3,"time":"2022-05-05T21:19:20+00:00","remoteAddr":"10.0.1.61","user":"3068AB2C-4706-4705-86D8-F14F237C43DC","app":"PHP","method":"POST","url":"/index.php/apps/libresign/api/0.1/sign/register"
,"message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php#41","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.4.1",
"Exception":{
"Exception":"Error"
,"message":"Trying to access array offset on value of type null at /var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php#41","Code":0,
"Trace":[{"file":"/var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php","line":41,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":240,"function":"getMetadata","class":"OCA\\Libresign\\Service\\PdfParserService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":222,"function":"getFileMetadata","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":172,"function":"saveFile","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Controller/SignFileController.php","line":88,"function":"save","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"requestSign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},
{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},
{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}

{"reqId":"2rjwy32NYIuJ81XN0nd1","level":3,"time":"2022-05-05T21:19:20+00:00","remoteAddr":"10.0.1.61","user":"3068AB2C-4706-4705-86D8-F14F237C43DC","app":"PHP","method":"POST","url":"/index.php/apps/libresign/api/0.1/sign/register"
,"message":"Invalid argument supplied for foreach() at /var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php#41","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.127 Safari/537.36","version":"23.0.4.1",
"Exception":{
"Exception":"Error"
,"message":"Invalid argument supplied for foreach() at /var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php#41","Code":0,
"Trace":[{"file":"/var/www/nextcloud/apps/libresign/lib/Service/PdfParserService.php","line":41,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":240,"function":"getMetadata","class":"OCA\\Libresign\\Service\\PdfParserService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":222,"function":"getFileMetadata","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Service/SignFileService.php","line":172,"function":"saveFile","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/apps/libresign/lib/Controller/SignFileController.php","line":88,"function":"save","class":"OCA\\Libresign\\Service\\SignFileService","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":217,"function":"requestSign","class":"OCA\\Libresign\\Controller\\SignFileController","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":126,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},
{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},
{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},
{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}

```

Also getting a memory error when trying to sign, tried doubling PHP memory limit
```
{"reqId":"5GnjpOxwNn17oNK5q4Lw","level":3,"time":"2022-05-05T21:14:29+00:00","remoteAddr":"10.0.1.65","user":"someuser@gmail.com","app":"PHP","method":"POST","url":"/index.php/apps/libresign/api/0.1/sign/uuid/27195478-b323-4695-a7fe-4be0848c5cbb",
"message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at /var/www/nextcloud/apps/libresign/vendor/libresign/tcpdi_parser/src/tcpdi_parser.php#891","userAgent":"Mozilla/5.0 (Linux; Android 12; Pixel 6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Mobile Safari/537.36","version":"23.0.4.1"}
```

### LINKED ISSUE #810: Error libresign-cli
Hello,
I have a problem on Libresign, as soon as I send an email to sign, I get the error "Unable to obtain the metadata of this file. Check if you have correctly installed libresign-cli.", I upload libresign-cli with "sudo -u www-data php occ libresign:install –cli" or  "sudo -u www-data php occ libresign:install –all" but I still have the same errors.

I also had errors when installing libresign but I changed some folders to replace it with fixed code from github

 - OS: [Ubuntu 20.04]
 - Browser [edge]
 - LibreSign Version [5.1.1]
 - Nextcloud Server Version [24]
 - Logs (Impossible get metadata from this file. Check if you installed correctly the libresign-cli)

### PR DESCRIPTION
**Pull request by vitormattos**
close #798
close #810

### CODE REVIEW

File: lib/Service/PdfParserService.php [hunk 1]
```diff
@@ -39,7 +39,7 @@ private function getDataDir(): string {
 	 */
 	public function getMetadata(string $filePath): array {
 		$fullPath = $this->getDataDir() . $filePath;
-		$json = shell_exec($this->cliPath . ' info ' . $fullPath);
+		$json = shell_exec($this->cliPath . ' info "' . escapeshellcmd($fullPath) . '"');
```
Comment (myzhang1029) [inline lib/Service/PdfParserService.php:42]: I believe it is better to use `escapeshellarg`, i.e.
```
shell_exec(escapeshellarg($this->cliPath) . ' info ' . escapeshellarg($fullPath));
```
because `escapeshellcmd` only escapes `"`s if they are not paired. One can still execute arbitrary commands by using a filename like `my"custom $(rm -rf /)" file.pdf`.

Comment (vitormattos) [reply lib/Service/PdfParserService.php:42]: The property `cliPath` come from `libresign_cli_path` app value and is defined by application not by user, but, I will check the impact.
